name: "Consensus Warn"

permissions: read-all

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    permissions:
      pull-requests: write # For reading the PR and posting comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: orijtech/consensuswarn@main
        with:
          roots: "github.com/BFH-FinTech-Innovations-Ltd/BFH-EVM/app.Evmos.FinalizeBlock,github.com/BFH-FinTech-Innovations-Ltd/BFH-EVM/app.Evmos.BeginBlocker,github.com/BFH-FinTech-Innovations-Ltd/BFH-EVM/app.Evmos.EndBlocker"
